import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbPage,
  BreadcrumbSeparator,
} from "@workspace/ui/components/breadcrumb";
import { Separator } from "@workspace/ui/components/separator";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@workspace/ui/components/sidebar";
import type { Metadata } from "next";
import { redirect } from "next/navigation";
import { AppSidebar } from "@/components/app-sidebar";
import { ThemeToggle } from "@/components/theme-toggle";
import {
  getAuthorizationContext,
  getPrimaryRole,
  hasAnyPermission,
  hasPermission,
  PERMISSIONS,
} from "@/lib/authorization";
import { getCurrentDatabaseUser } from "@/lib/current-user";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const authorization = await getAuthorizationContext();
  if (!authorization) redirect("/auth/login");

  const user = await getCurrentDatabaseUser();
  const role = getPrimaryRole(authorization);
  const roleLabel = {
    administrator: "Administrador",
    author: "Autor",
    patient: "Paciente",
  }[role];
  const userData = {
    name: user.name,
    email: user.email || "E-mail não informado",
    avatar: user.picture || "/avatars/shadcn.jpg",
  };

  return (
    <SidebarProvider>
      <AppSidebar
        user={userData}
        access={{
          roleLabel,
          canReadArticles: hasAnyPermission(authorization, [
            PERMISSIONS.readOwnArticles,
            PERMISSIONS.readAnyArticles,
          ]),
          canCreateArticles: hasPermission(
            authorization,
            PERMISSIONS.createArticles,
          ),
          canManageSite: hasPermission(authorization, PERMISSIONS.manageSite),
          canReadUsers: hasPermission(authorization, PERMISSIONS.readUsers),
        }}
      />
      <SidebarInset className="px-4">
        <header className="flex h-16 shrink-0 items-center gap-2 transition-[width,height] ease-linear group-has-data-[collapsible=icon]/sidebar-wrapper:h-12">
          <div className="flex items-center gap-2">
            <SidebarTrigger className="-ml-1" />
            <Separator
              orientation="vertical"
              className="mr-2 data-[orientation=vertical]:h-4"
            />
            <Breadcrumb>
              <BreadcrumbList>
                <BreadcrumbItem className="hidden md:block">
                  <BreadcrumbLink href="#">Kianda</BreadcrumbLink>
                </BreadcrumbItem>
                <BreadcrumbSeparator className="hidden md:block" />
                <BreadcrumbItem>
                  <BreadcrumbPage>Page</BreadcrumbPage>
                </BreadcrumbItem>
              </BreadcrumbList>
            </Breadcrumb>
          </div>
          <div className="ml-auto flex items-center gap-2">
            <ThemeToggle />
          </div>
        </header>
        {children}
      </SidebarInset>
    </SidebarProvider>
  );
}
